[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  BUILD_VERSION = "v10"

# SPA routing (redundant to public/_redirects, but ok)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
